## Numpy

#### a fundamental library for scientific computing in python. It provides support for arrays and matrices along with a collection of mathematical functions to operate on these data structures

In [4]:
!pip install numpy

In [5]:
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
#two dimensional array
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [7]:
##two dimensional array
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [8]:
np.arange(0,10,2).reshape((5,1))

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
##Identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print('Array:\n',arr)
print('Shape of the array:', arr.shape)
print('Number of dimensions:', arr.ndim)
print('Size (numbetr of elements):', arr.size)
print('Data type:', arr.dtype)
print('Item size (in bytes):', arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the array: (3, 3)
Number of dimensions: 2
Size (numbetr of elements): 9
Data type: int64
Item size (in bytes): 8


In [12]:
### Numpy vectorized operations

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

##Element wise addition

print('Addition:',arr1 + arr2)
##Element wise substraction
print('Substraction:',arr1 - arr2)
##Element wise multiplication
print('Multiplication:',arr1 * arr2)
##Element wise division
print('Division:',arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
### Universal functions
arr = np.array([1, 4, 9, 16, 25])

##Square root
print('Square root:',np.sqrt(arr))

##Exponential
print('Exponential:',np.exp(arr))

##Sine
print('Sine:',np.sin(arr))

##Natural logarithm
print('Natural logarithm:',np.log(arr))

Square root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Natural logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [14]:
## array slicing and indexing

arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [18]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [21]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [22]:
##Modify array elements

arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [25]:
## statistical concepts --- Normalization
## to have a mean of 0 and a standard deviation of 1


data = np.array([10, 20, 30, 40, 50])

#calculate mean and standard deviation
mean = np.mean(data)
print('Mean: ',mean)
std_dev= np.std(data)
print('Standard Deviation: ',std_dev)

#Median
median=np.median(data)
print('Median: ',median)
#Variance
variance=np.var(data)
print('Variance: ',variance)

#normalize the data
normalized_data=(data-mean)/std_dev
print('Normalized data:',normalized_data)




Mean:  30.0
Standard Deviation:  14.142135623730951
Median:  30.0
Variance:  200.0
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [29]:
##Logical operations

data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
print(data[(data>5) & (data<=8)])

[False False False False False  True  True  True  True  True]
[6 7 8]
